# Generated by Django 4.1.7 on 2023-03-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='google_plus_link',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='twitter_link',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
    ]
